# -*- coding: utf-8 -*-
"""FinalMLproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19zXcnhwNzlm6losjvtMgR7HPAUvTFAqn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.integrate import odeint
from scipy.optimize import least_squares

plt.style.use("seaborn-v0_8")
plt.rcParams["figure.figsize"] = (12,6)

cases_df = pd.read_csv("covid_19_india.csv")
vaccine_df = pd.read_csv("covid_vaccine_statewise.csv")
testing_df = pd.read_csv("StatewiseTestingDetails.csv")

cases_df.head(),vaccine_df.head(), testing_df.head()

# Convert date column
cases_df['Date'] = pd.to_datetime(cases_df['Date'], dayfirst=True)

# Compute national confirmed daily
national = cases_df.groupby("Date").agg({
    "Confirmed": "sum",
    "Cured": "sum",
    "Deaths": "sum"
}).sort_values("Date")

# Compute daily new cases
national['New_Cases'] = national['Confirmed'].diff().fillna(national['Confirmed'].iloc[0])
national.head()

fig, ax = plt.subplots(2,1, figsize=(14,10), sharex=True)

ax[0].plot(national.index, national['Confirmed'], label="Cumulative Confirmed")
ax[0].set_ylabel("Cases")
ax[0].legend()

ax[1].bar(national.index, national['New_Cases'], label="Daily New Cases")
ax[1].set_ylabel("Daily Cases")
ax[1].legend()

plt.title("COVID-19 National Case Trend")
plt.show()

national["New_Smoothed"] = national["New_Cases"].rolling(7, min_periods=1).mean()

# Fix missing values if any
national = national.fillna(0)

national.tail()

POP = 1380000000  # India's population
data = national.copy()

# Model uses CUMULATIVE infected for fitting
infected_data = data['Confirmed'].values

# Days timeline
t = np.arange(len(infected_data))

def seir(y, t, N, beta, sigma, gamma):
    S, E, I, R = y
    dSdt = -beta * S * I / N
    dEdt = beta * S * I / N - sigma * E
    dIdt = sigma * E - gamma * I
    dRdt = gamma * I
    return [dSdt, dEdt, dIdt, dRdt]

def run_seir(beta, sigma, gamma, N, E0, I0, R0, days):
    S0 = N - E0 - I0 - R0
    y0 = [S0, E0, I0, R0]
    sol = odeint(seir, y0, np.arange(days), args=(N, beta, sigma, gamma))
    return sol

# Initial guesses
sigma = 1/5  # incubation ~5 days
beta_guess = 0.4
gamma_guess = 1/10  # recovery ~10 days

I0 = infected_data[1]  # initial infected
E0 = I0 * 2            # assume exposed = 2x infected
R0 = national["Cured"].iloc[0]

def loss(params):
    beta, gamma = params
    pred = run_seir(beta, sigma, gamma, POP, E0, I0, R0, len(t))
    S, E, I, R = pred.T
    infected_pred = I + R
    return infected_pred - infected_data

result = least_squares(loss, [beta_guess, gamma_guess], bounds=(0,5))
beta_fit, gamma_fit = result.x
beta_fit, gamma_fit

final = run_seir(beta_fit, sigma, gamma_fit, POP, E0, I0, R0, len(t))
S,E,I,R = final.T

plt.plot(data.index, infected_data, label="Actual")
plt.plot(data.index, I+R, label="SEIR Prediction")
plt.legend()
plt.title("SEIR Model Fit")
plt.show()

future_days = 60

forecast = run_seir(beta_fit, sigma, gamma_fit, POP, E0, I0, R0, len(t)+future_days)
Sf, Ef, If, Rf = forecast.T

plt.plot(np.arange(len(t)), infected_data, label="Actual")
plt.plot(np.arange(len(t)), If[:len(t)] + Rf[:len(t)], label="Model Fit")
plt.plot(np.arange(len(t), len(t)+future_days), If[-future_days:] + Rf[-future_days:], '--', label="Forecast")

plt.legend()
plt.title("60-Day Forecast")
plt.show()

